<div id="site-blogs">
  <h1>Venture Capital and Angel Investment Blogs</h1>
  Below you will find an extensive list of blogs from established venture capitalists, venture capital firms, 
  as well as individual business angels. If you have a blog that you feel should be included here, please
  <?php print l('send us a link', 'contact') ?> and we will update the list.
  <div id="blogs-left">
    <h2>Venture Capitalist Blogs</h2>
    <ul>
      <li>Adam Fisher - <a href="http://savantsinthelevant.blogspot.com/">Savants In The Levant</a></li>
      <li>Adi Pundak-Mintz - <a href="http://adisababa.wordpress.com/">Adisababa's Weblog</a></li>
      <li>Alan Veeck - <a href="http://www.pittsburghventures.com/">Pittsburgh Ventures</a></li>
      <li>Albert Wenger - <a href="http://continuations.com/">Continuations</a></li>
      <li>Alfonso Urien <em>(Spanish)</em> - <a href="http://entrinnova.wordpress.com/">Entrinnova's Weblog</a></li>
      <li>Allen Morgan - <a href="http://allensblog.typepad.com/">Allen's Blog</a></li>
      <li>Alok Mittal - <a href="http://www.venturewoods.org/">VentureWoods</a></li>
      <li>Anand Sridharan - <a href="http://radventure.blogspot.com/">Seriously Clueless</a></li>
      <li>Andrew Parker - <a href="http://radventure.blogspot.com/">Andrew Parker - The Gong Show</a></li>
      <li>Anthony Tjan - <a href="http://blogs.hbr.org/tjan/">Anthony Tjan - Harvard Business Review</a></li>
      <li>Anupendra Sharma - <a href="http://anupendra.blogspot.com/">So Little Time, So Much...</a></li>
      <li>Art Marks - <a href="http://thequest.typepad.com/">Entrepreneurial Quest</a></li>
      <li>Ashu Garg - <a href="http://ashugarg.com/">Ashu Garg's Blog</a></li>
      <li>Austin Hill - <a href="http://www.billionswithzeroknowledge.com/">Billions With Zero Knowledge</a></li>
      <li>Baris Karadogan - <a href="http://baris.typepad.com/">From Istanbul To Sand Hill Road</a></li>
      <li>Bijan Sabet - <a href="http://bijansabet.com/">Bijan Sabet's Tumblelog</a></li>
      <li>Bill Gurley - <a href="http://abovethecrowd.com/">Above The Crowd</a></li>
      <li>Boris Wertz - <a href="http://www.wmediaventures.com/blog/">W Media Ventures</a></li>
      <li>Brad Burnham - <a href="http://bradburnham.tumblr.com/">Unfinished Work</a></li>
      <li>Brad Feld - <a href="http://www.feld.com/">Feld Thoughts</a></li>
      <li>Brian Feinstein - <a href="http://www.brianfeinstein.com/">Brian Feinstein</a></li>
      <li>Brian Hirsch - <a href="http://www.ny-vc.com/">New York VC</a></li>
      <li>Cem Sertoglu - <a href="http://csertoglu.typepad.com">SortiPreneur</a></li>
      <li>Charles Curran - <a href="http://charlescurran.typepad.com/">VC Blog On Storage, Wireless/VoIP, Internet</a></li>
      <li>Charlie Federman - <a href="http://www.charlie-federman.blogspot.com/">Cosmic VC</a></li>
      <li>Charlie Kemper - <a href="http://blog.kmf.net/">Digital Rubicon Musings</a></li>
      <li>Charlie O'Donnell - <a href="http://www.thisisgoingtobebig.com/">This Is Going To Be BIG!</a></li>
      <li>Chip Hazard - <a href="http://hazard.typepad.com/">Hazard Lights</a></li>
      <li>Chris Arsenault - <a href="http://chrisarsenault.wordpress.com/">Chris Arsenault's Blog</a></li>
      <li>Chris Fralic - <a href="http://nothingtosay.firstround.com/">Nothing To Say</a></li>
      <li>Chris Freund - <a href="http://chrisfreund.blogspot.com/">Chris Freund's Vietnam Private Equity Blog</a></li>
      <li>Christian Leybold - <a href="http://blogging.vc/">Blogging VC</a></li>
      <li>Christian Mayaud - <a href="http://www.sacredcowdung.com/">Sacred Cow Dung</a></li>
      <li>Christine Herron - <a href="http://www.christine.net">Christine</a></li>
      <li>Clint Chao - <a href="http://clintchao.tumblr.com/">The Good Stuff In The Seller</a></li>
      <li>Cynthia Trevino - <a href="http://www.smallcompanybigimage.com/">Small Company Big Image</a></li>
      <li>Dan Rua - <a href="http://floridaventureblog.com/">Florida Venture Blog</a></li>
      <li>Daniel Cohen - <a href="http://coheda.typepad.com/">Israel Venture Capital 2.0</a></li>
      <li>David Anderson - <a href="http://supplychainventures.typepad.com/">A VC In Vacationland</a></li>
      <li>David Aronoff - <a href="http://www.geekvc.com/">Diary Of a Geek VC</a></li>
      <li>David Beisel - <a href="http://www.genuinevc.com/">Genuine VC</a></li>
      <li>David Cowan - <a href="http://whohastimeforthis.blogspot.com/">Who Has Time For This?</a></li>
      <li>David Dufresne - <a href="http://capital-risqueur.blogspot.com/">Dav-Generated Content</a></li>
      <li>David Feinleib - <a href="http://www.vcdave.com/">Tech, Startups, Capital, Ideas</a></li>
      <li>David Hornik - <a href="http://ventureblog.com/">VentureBlog</a></li>
      <li>David Pakman - <a href="http://dpakman.wordpress.com/">Pakman's Blog: Disruption</a></li>
      <li>David Stern - <a href="http://www.davidlstern.com/">The Raging Insterno</a></li>
      <li>David Tze - <a href="http://www.aquacopia.com/">Aquacopia</a></li>
      <li>Derek Pilling - <a href="http://derekpilling.com/">Non-Linear VC</a></li>
      <li>Dev Khare - <a href="http://www.nextwala.com/">NextWala</a></li>
      <li>Don Rainey - <a href="http://startups.typepad.com/">VC In DC</a></li>
      <li>Ed French - <a href="http://www.techgain.net/">TechGain</a></li>
      <li>Ed Mlavsky - <a href="http://golb.typepad.com/">GOLB: Is This Israel?</a></li>
      <li>Ed Sim - <a href="http://www.beyondvc.com/">Beyond VC</a></li>
      <li>Edward Stadum - <a href="http://toxicvc.blogspot.com/">The Toxic German VC Legal Landscape</a></li>
      <li>Eric Friedman - <a href="http://www.marketing.fm/">Eric Friedman - Marketing.fm</a></li>
      <li>Eric Ver Ploeg - <a href="http://verploeg.com/PocketWatch/">Pocket Watch</a></li>
      <li>Eric Wiesen, Stuart Ellman - <a href="http://fiveyearstoolate.wordpress.com/">Five Years Too Late</a></li>
      <li>Evangelos Simoudis - <a href="http://blog.tridentcap.com/">Trident Capital Blog</a></li>
      <li>Fred Destin - <a href="http://www.freddestin.com/">Fred Destin</a></li>
      <li>Fred Wilson - <a href="http://www.avc.com/">A VC</a></li>
      <li>George Zachary - <a href="http://senseandcents.blogspot.com/">Sense And Cents</a></li>
      <li>Gil Dibner - <a href="http://techtlv.com/blog/">TechTLV: Notes On Innovation From The Med</a></li>
      <li>Greg Foster - <a href="http://southernvc.com/">Southern VC</a></li>
      <li>Gregoire Aladjidi - <a href="http://techfundinfo.wordpress.com/">Investing In What's Next</a></li>
      <li>Guy Kawasaki - <a href="http://blog.guykawasaki.com/">How To Change The World</a></li>
      <li>Hernan Pisano - <a href="http://nextlogics.wordpress.com/">Nextlogics's Weblog</a></li>
      <li>Ho Nam - <a href="http://altos.typepad.com/">Altos Ventures Musings</a></li>
      <li>Howard Morgan - <a href="http://waytooearly.firstround.com/">Way Too Early</a></li>
      <li>Jacob Ner-David - <a href="http://vcinjerusalem.typepad.com/">VC In Jerusalem</a></li>
      <li>James Chen - <a href="http://www.purevc.com/">Pure VC</a></li>
      <li>James D. Robinson IV - <a href="http://jdriv.blogspot.com/">Jdrive</a></li>
      <li>Jason Ball - <a href="http://www.jasonball.com/">Jason Ball's TechBytes</a></li>
      <li>Jason Caplain - <a href="http://southeastvc.blogs.com/">Southeast VC</a></li>
      <li>Jason Mendelson - <a href="http://www.askthevc.com/">Ask The VC</a></li>
      <li>Jean-Luc Park - <a href="http://www.j-lp.com/blog/">I Am Now, Have Been, And Will Be Wrong</a></li>
      <li>Jeff Bocan - <a href="http://www.huffingtonpost.com/jeff-bocan">Jeff Bocan</a></li>
      <li>Jeff Bussgang - <a href="http://bostonvcblog.typepad.com/">Seeing Both Sides</a></li>
      <li>Jeff Clavier - <a href="http://blog.softtechvc.com/">Jeff Clavier's Software Only</a></li>
      <li>Jeff Joseph - <a href="http://venturepopulist.com/">Venture Populist</a></li>
      <li>Jeremy Levine - <a href="http://nothingventurednothinggained.blogspot.com/">Nothing Ventured, Nothing Gained</a></li>
      <li>Jeremy Liew - <a href="http://lsvp.wordpress.com/">Lightspeed Venture Partners Blog</a></li>
      <li>Jim Armstrong - <a href="http://socalvc.blogspot.com/">SoCal VC</a></li>
      <li>Jim Butz - <a href="http://socalbuzz.wordpress.com/">SoCal Buzz</a></li>
      <li>John Abraham - <a href="http://abejma.blogspot.com/">JMA's Views On Everything</a></li>
      <li>John Brimacombe - <a href="http://skylander2000.wordpress.com/">John M. Brimacombe's Blog</a></li>
      <li>John Ludwig - <a href="http://theludwigs.com/">A Little Ludwig Goes a Long Way</a></li>
      <li>John Reed - <a href="http://southwestventure.com/">Southwest Venture</a></li>
      <li>John Thornton - <a href="http://insomniactive.com/">Insomniactive</a></li>
      <li>Joi Ito - <a href="http://joi.ito.com/">Joi Ito's Web</a></li>
      <li>Jon Seeber - <a href="http://vcjon.blogspot.com/">Jon's Ventures</a></li>
      <li>Jon Steinberg - <a href="http://jonsteinberg.com/">Jon Steinberg</a></li>
      <li>Jonathan Tower - <a href="http://jonathantower.wordpress.com/">Adventure Capitalist</a></li>
      <li>Josh Kopelman - <a href="http://redeye.firstround.com/">Redeye VC</a></li>
      <li>Josh Sookman - <a href="http://www.startuplifeblog.com/">Startup Life</a></li>
      <li>Juha Christensen - <a href="http://www.juhachristensen.com/">Juha Christensen's Mobile Experiences</a></li>
      <li>Justin Label - <a href="http://ventureagain.blogspot.com/">Venture Again</a></li>
      <li>Kent Goldman - <a href="http://thecornice.com/">The Cornice</a></li>
      <li>Larry Cheng - <a href="http://larrycheng.com/">Thinking About Thinking</a></li>
      <li>Larry Marcus - <a href="http://wvcblog.blogspot.com/">Walden Venture Capital Views and News</a></li>
      <li>Lee Hower - <a href="http://www.leehower.com/">Venturesome</a></li>
      <li>Marc Andreessen - <a href="http://blog.pmarca.com/">Marc Andreessen</a></li>
      <li>Marc Averitt - <a href="http://ocvcblog.com/">OC VC</a></li>
      <li>Marc Goldberg - <a href="http://mgoldberg.typepad.com/">Occam's Razor</a></li>
      <li>Marcus Ogawa - <a href="http://www.questvp.com/index.php/blog">Quest Venture Partners</a></li>
      <li>Mark Peter Davis - <a href="http://www.markpeterdavis.com/">Venture Made Transparent</a></li>
      <li>Mark Sherman - <a href="http://www.abcdvc.com/">ABCDVC</a></li>
      <li>Mark Suster - <a href="http://bothsidesofthetable.com/">Both Sides Of The Table</a></li>
      <li>Matt McCall - <a href="http://www.vcconfidential.com/">VC Confidential</a></li>
      <li>Matt Winn - <a href="http://punctuative.com/">Punctuative!</a></li>
      <li>Max Bleyleben - <a href="http://maxbley.typepad.com/">Technofile Europe</a></li>
      <li>Max Niederhofer - <a href="http://maxniederhofer.com/">Max Niederhofer</a></li>
      <li>Michael Eisenberg - <a href="http://sixkidsandafulltimejob.blogspot.com/">Six Kids And a Full Time Job</a></li>
      <li>Michael Feinstein - <a href="http://www.thefeinline.com/">The Fein Line</a></li>
      <li>Michael Greeley - <a href="http://ontheflyingbridge.wordpress.com/">On The Flying Bridge</a></li>
      <li>Michelle Goldberg - <a href="http://www.vcmom.com/">VC Mom</a></li>
      <li>Mike Hirshland - <a href="http://vcmike.wordpress.com/">VCMike's Blog</a></li>
      <li>Mike Speiser - <a href="http://laserlike.com/">Laserlike</a></li>
      <li>Mitch Lasky - <a href="http://bizpunk.blogspot.com/">Bizpunk</a></li>
      <li>Mo Koyfman - <a href="http://www.mokoyfman.com/">Mo Koyfman</a></li>
      <li>Morten Lund - <a href="http://lundxy.com/">Morten Lund - LundXY - It's All About Luck</a></li>
      <li>Nader Ghaffari - <a href="http://www.sandhillblogger.com/">Sand Hill Blogger</a></li>
      <li>Naval Ravikant - <a href="http://www.startupboy.com/">Startup Boy</a></li>
      <li>Nic Brisbourne - <a href="http://www.theequitykicker.com/">The Equity Kicker</a></li>
      <li>Nicholas Chan - <a href="http://nicholas-chan.blogspot.com/">The Accidental Venture Capitalist</a></li>
      <li>Olaf Jacobi - <a href="http://olafjacobi.wordpress.com/">Beyond Limits</a></li>
      <li>Om Malik - <a href="http://omis.me/">Om Malik</a></li>
      <li>Pablo Brenner <em>(Spanish)</em> - <a href="http://pablobrenner.wordpress.com/">Pablo Brenner &amp; Sergio Fogel Blog</a></li>
      <li>Paco Sandejas - <a href="http://phil-bgn.blogspot.com/">Tapping The Brain Gain Network</a></li>
      <li>Pascal Levensohn - <a href="http://www.pascalsview.com/">Pascal's View</a></li>
      <li>Paul Fisher - <a href="http://www.thecoffeeshopsofmayfair.com/">The Coffee Shops Of Mayfair</a></li>
      <li>Paul Jozefak - <a href="http://babblingvc.typepad.com/">Babbling VC</a></li>
      <li>Paul Kedrosky - <a href="http://paul.kedrosky.com/">Paul Kedrosky's Infectious Greed</a></li>
      <li>Peter Lee - <a href="http://seeingeyetoeye.wordpress.com/">Seeing Eye To Eye</a></li>
      <li>Peter Rip - <a href="http://earlystagevc.typepad.com/">Early Stage VC</a></li>
      <li>Peter Zaballos - <a href="http://openambition.com/">Open Ambition</a></li>
      <li>Philippe Botteri - <a href="http://cracking-the-code.blogspot.com/">Cracking The Code</a></li>
      <li>Phin Barnes - <a href="http://www.sneakerheadvc.com/">Sneakerhead VC</a></li>
      <li>Rajil Kapoor - <a href="http://vcinme.typepad.com/">The VC In Me...</a></li>
      <li>Randall Lucas - <a href="http://blog.rlucas.net/">The Next Generation</a></li>
      <li>Rich Barton - <a href="http://www.hopperanddropper.com/">Hopper And Dropper</a></li>
      <li>Richard Dale - <a href="http://venturecyclist.blogspot.com/">Venture Cyclist</a></li>
      <li>Richard Moran - <a href="http://www.moranatwork.com/">Moran at Work</a></li>
      <li>Rob Coppedge - <a href="http://nextthingsfirst.wordpress.com/">Next Things First</a></li>
      <li>Rob Day - <a href="http://www.greentechmedia.com/cleantech-investing/">Cleantech Investing</a></li>
      <li>Rob Finn - <a href="http://www.ventureblogalist.com/">Ventureblogalist</a></li>
      <li>Rob Go - <a href="http://www.robgo.org/">Rob Go</a></li>
      <li>Rob Hayes - <a href="http://permanentrecord.firstround.com/">Permanent Record</a></li>
      <li>Rob Schultz - <a href="http://www.robschultz.com/">Go Big Or Go Home</a></li>
      <li>Rob Shurtleff - <a href="http://www.shurtleff.org/">Rob's Reflections</a></li>
      <li>Robert Goldberg - <a href="http://robertgoldberg.typepad.com/">Tahoe VC</a></li>
      <li>Ryan McIntyre - <a href="http://www.ryanmcintyre.com/">McInblog</a></li>
      <li>Ryan Spoon - <a href="http://ryanspoon.com/">Ryan Spoon</a></li>
      <li>Sagi Rubin - <a href="http://sagi.typepad.com/">The Grass Is "Greener"</a></li>
      <li>Salman Farmanfarmaian - <a href="http://salmanff.blogspot.com/">Salman's Blog</a></li>
      <li>Sandy Hamilton - <a href="http://sandyhamilton.blogs.com/">Sandy Hamilton - Perspectives</a></li>
      <li>Santo Politi - <a href="http://santopoliti.tumblr.com/">This And That</a></li>
      <li>Sarah Tavel - <a href="http://www.adventurista.com/">Adventurista</a></li>
      <li>Satya Patel - <a href="http://venturegeneratedcontent.com/">Venture Generated Content</a></li>
      <li>Saul Klein - <a href="http://localglobe.blogspot.com/">Saul Klein</a></li>
      <li>Scott Maxwell - <a href="http://blog.openviewpartners.com/blog/now-what/">Now What?</a></li>
      <li>Sean Park - <a href="http://www.parkparadigm.com/">The Park Paradigm</a></li>
      <li>Seth Levine - <a href="http://www.sethlevine.com/">Seth Levine's VC Adventure</a></li>
      <li>Shin Fukushige - <a href="http://fukumimi.wordpress.com/">From The Inside, Looking In</a></li>
      <li>Simon Olson - <a href="http://galaxy.blogs.com/">Venture Capital Thoughts And Reflections</a></li>
      <li>Stephan Gueorguiev - <a href="http://cleanthoughts.typepad.com/">Clean Thoughts</a></li>
      <li>Stephen Fleming - <a href="http://academicvc.com/">Academic VC</a></li>
      <li>Steve Brotman - <a href="http://brotman.blogs.com/">VCball</a></li>
      <li>Steve Jurvetson - <a href="http://jurvetson.blogspot.com/">The J Curve</a></li>
      <li>Stewart Alsop - <a href="http://www.stewartalsop.com/">Alsop's Small Thoughts</a></li>
      <li>Stu Phillips - <a href="http://1vc.typepad.com/">Soaring on Ridgelift</a></li>
      <li>Ted Driscoll - <a href="http://evolvingvc.blogspot.com/">Evolving VC</a></li>
      <li>Ted Rogers - <a href="http://vc-brazil.com/blog/">Venture Capital Brazil</a></li>
      <li>Tim Dick - <a href="http://www.usehalf.com/blog/blog.php">UseHalf Conservation Without Compromise</a></li>
      <li>Tim Draper - <a href="http://theriskmaster.blogspot.com/">The Riskmaster</a></li>
      <li>Tim Oren - <a href="http://due-diligence.typepad.com/">Tim Oren's Due Diligence</a></li>
      <li>Todd Dagres - <a href="http://todddagres.tumblr.com/">Todd Dagres Tumblog</a></li>
      <li>Todd Jaquez-Fissori	- <a href="http://outrightvc.com/">Fissori's Outright Venture Blog</a></li>
      <li>Todd Klein - <a href="http://wildrumpus.typepad.com/">Media VC</a></li>
      <li>Toni Schneider - <a href="http://toni.org/">Toni Schneider</a></li>
      <li>Venky Ganesan - <a href="http://www.venchar.com/">VenChar</a></li>
      <li>Vishy Venugopalan - <a href="http://longworthvp.wordpress.com/">Longworth Venture Partners Blog</a></li>
      <li>Will Price - <a href="http://willprice.blogspot.com/">Will Price</a></li>
      <li>William Quigley - <a href="http://quigleyreport.blogspot.com/">The Quigley Report</a></li>
      <li><em>Unknown Author</em> - <a href="http://www.theprivateequiteer.com/">The Private Equiteer</a></li>
      <li><em>Various Authors</em> - <a href="http://www.nwventurevoice.com/">NW Venture Voice</a></li>
    </ul>
  </div>
  <div id="blogs-right">
    <h2>VC Firm Blogs</h2>
    <ul id="firm-blogs">
      <li>Brightspark Ventures - <a href="http://blog.brightspark.com/">Let The Sparks Fly!</a></li>
      <li>CavaCapital - <a href="http://cavacapital.wordpress.com/">CavaCapital's Blog</a></li>
      <li>Foundry Group - <a href="http://www.foundrygroup.com/wp/">Foundry Group Blog</a></li>
      <li>Golden Horn Ventures - <a href="http://goldenhornventures.typepad.com/">Golden Horn Ventures Blog</a></li>
      <li>Highway 12 Ventures - <a href="http://www.highway12ventures.com/blog/">Group Blog</a></li>
      <li>Tech Capital Partners - <a href="http://blog.techcapital.com/">Tech Capital Partners Blog</a></li>
      <li>True Ventures - <a href="http://www.trueventures.com/blog/">More Venture, Less Capital</a></li>
      <li>Union Square Ventures - <a href="http://www.unionsquareventures.com/">Union Square Ventures Blog</a></li>
      <li>Volition Capital - <a href="http://ask.volitioncapital.com/ask/">Ask Volition</a></li>
      <li>Walden Venture Capital - <a href="http://wvcblog.blogspot.com/">Walden Venture Capital</a></li>
    </ul>
    <h2>Angel Investor Blogs</h2>
    <ul id="angel-blogs">
      <li>Adam Jackson - <a href="http://jacksonfound.com/">Entrepreneur, Investor, Advisor</a></li>
      <li>Adam Messinger - <a href="http://radar.oreilly.com/adam/">Adam Messinger | O'Reilly Radar</a></li>
      <li>Albert Armengol <em>(Spanish)</em> - <a href="http://www.albertarmengol.net/">Endocitosis De Red</a></li>
      <li>Alberto Knapp Bjeren <em>(Spanish)</em> - <a href="http://www.the-mixer.net/">The Mixer - La Coctelera</a></li>
      <li>Alex Karakozoff - <a href="http://startupsalesvp.blogspot.com/">Experience Driven Advice For Start Up CEO's</a></li>
      <li>Andy Liu - <a href="http://www.inspiredstartup.com/">Inspired Startup</a></li>
      <li>Andy Sack - <a href="http://asack.typepad.com/">A Sack Of Seattle</a></li>
      <li>Ari Newman - <a href="http://www.newmanva.com/blog/">The NVA Blog</a></li>
      <li>Ariel Arrieta <em>(Spanish)</em> - <a href="http://arielarrieta.com/">Ariel Arrieta's Blog</a></li>
      <li>Auren Hoffman - <a href="http://summation.typepad.com">Summation</a></li>
      <li>Axel Serena <em>(Spanish)</em> - <a href="http://www.axelserena.com/">Axel Serena</a></li>
      <li>Aydin Senkut - <a href="http://felicis.typepad.com/blog/">Felicis Ventures Blog</a></li>
      <li>Barry Harrigan - <a href="http://www.acceleratingitsales.com/">Accelerating IT Sales</a></li>
      <li>Basil Peters - <a href="http://www.angelblog.net/">Best Practices For Angels And Entrepreneurs</a></li>
      <li>Bernard Leong - <a href="http://www.bernardleong.com/">Bernard Leong</a></li>
      <li>Bill Barhydt - <a href="http://billbar.wordpress.com/">A Tech CEO. Musings, Rants &amp; Raves</a></li>
      <li>Bill Flagg - <a href="http://billflagg.blogspot.com/">Bill Flagg</a></li>
      <li>Bill Lemon - <a href="http://www.cleantechfinance.typepad.com/">Cleantech Finance Insider</a></li>
      <li>Bill Payne - <a href="http://www.theicehouse.co.nz/Internal/InternalBlogs/AngelsBlog/tabid/236/Default.aspx">Bill Payne's Blog</a></li>
      <li>Bipin Agarwal - <a href="http://twentyminutelifestyle.wordpress.com/">Twenty-Minute Lifestyle</a></li>
      <li>Boyan Josic - <a href="http://www.boyandigital.com/">Beyond Next</a></li>
      <li>Brant Bukowsky - <a href="http://www.angelinvestmentjournal.com/">Angel Investment Journal</a></li>
      <li>Brendan McLoughlin - <a href="http://brenmcl.blogspot.com/">Brendan's Blog</a></li>
      <li>Brian Berliner - <a href="http://www.brianberliner.com/">Brian Berliner's Brain</a></li>
      <li>Brian Sear - <a href="http://www.briansbusinessblog.com/">Brian's Business Blog</a></li>
      <li>Brock Blake - <a href="http://brockblake.com/">Angel Investing, Entrepreneurship &amp; Learning</a></li>
      <li>Carlos Blanco <em>(Spanish)</em> - <a href="http://www.carlosblanco.com/">Carlos Blanco</a></li>
      <li>Charlie Paparelli - <a href="http://paparelli.typepad.com/">Charlie Paparelli</a></li>
      <li>Chip Griffin - <a href="http://chipgriffin.com/">Pardon The Disruption</a></li>
      <li>Chris DeVore - <a href="http://crashdev.blogspot.com/">Crash Dev</a></li>
      <li>Chris Sacca - <a href="http://www.whatisleft.org/">Chris Sacca's 'What Is Left?'</a></li>
      <li>Chris Sheehan - <a href="http://earlystageadventures.com/">Early Stage Adventures</a></li>
      <li>Chris Yeh - <a href="http://chrisyeh.blogspot.com/">Adventures In Capitalism</a></li>
      <li>Christopher Allen - <a href="http://www.lifewithalacrity.com/">Life With Alacrity</a></li>
      <li>Clay Cook - <a href="http://claycook.wordpress.com/">Clay Cook</a></li>
      <li>Dan Malven - <a href="http://www.startupconversations.com/">Startup Conversations</a></li>
      <li>Dan Weinreb - <a href="http://danweinreb.org/blog/">Dan Weinreb's Blog</a></li>
      <li>Darren Hardy - <a href="http://darrenhardy.success.com/">Darren Hardy, Publisher Of SUCCESS Magazine</a></li>
      <li>Dave McClure - <a href="http://500hats.typepad.com/">Master Of 500 Hats</a></li>
      <li>Dave Moskovitz - <a href="http://nzangels.com/">NZ Angels</a></li>
      <li>David Cohen - <a href="http://www.coloradostartups.com/">Colorado Startups</a></li>
      <li>David Lerner - <a href="http://www.davidblerner.com/">David B. Lerner</a></li>
      <li>David S. Rose - <a href="http://www.rose.vc/angelnotes/">AngelNotes</a></li>
      <li>David Siegel - <a href="http://www.dsiegel.com/">David Siegel's Casbah</a></li>
      <li>Dharmesh Shah - <a href="http://onstartups.com/">On Startups by Dharmesh Shah</a></li>
      <li>Eric Marcoullier - <a href="http://www.marcoullier.com/">Marcoullier.com</a></li>
      <li>Florian Seroussi - <a href="http://www.florianseroussi.com">Florian's Blog</a></li>
      <li>Francisco Banha <em>(Portuguese)</em> - <a href="http://gesbanha.blogs.sapo.pt/">Francisco Banha Weblog</a></li>
      <li>Frank Peters - <a href="http://www.frankpetersshow.com/">The Frank Peters Show</a></li>
      <li>Frederik Fleck - <a href="http://frederikfleck.com/">Frederik Fleck's Blog</a></li>
      <li>Gaston Bercun <em>(Spanish)</em> - <a href="http://bercun.com.ar/blog/">El Blog De Gaston Bercun</a></li>
      <li>Gerry Campbell - <a href="http://luckyrobot.com/">Lucky Robot</a></li>
      <li>Greg Stuart - <a href="http://mansavesdog.wordpress.com/">ManSavesDog</a></li>
      <li>Herve Cuviliez - <a href="http://hervecuviliez.com/">Herve Cuviliez</a></li>
      <li>Hunter Walk - <a href="http://elapsedtime.blogspot.com/">Elapsed Time</a></li>
      <li>James Geshwiler - <a href="http://commonangels.wordpress.com/">Adventures In Startups &amp; VC</a></li>
      <li>Jason Tapolci - <a href="http://jasontapolci.wordpress.com/">Idea Funding Cafe Blog</a></li>
      <li>Jens Kunath <em>(German)</em> - <a href="http://www.jenskunath.eu/">Jens Kunath - Serial Entrepreneur</a></li>
      <li>Jesus Monleon <em>(Spanish)</em> - <a href="http://www.blogdeemprendedores.com/">Blog De Emprendedores</a></li>
      <li>Jim Donovan - <a href="http://jimdonovan.net.nz/">En Avant</a></li>
      <li>Joe Kraus - <a href="http://bnoopy.typepad.com/">Bnoopy</a></li>
      <li>John Borthwick - <a href="http://www.borthwick.com/weblog/">THINK / Musings</a></li>
      <li>John McKinley - <a href="http://greatfallsventures.wordpress.com/">Great Falls Ventures</a></li>
      <li>John Seiffer - <a href="http://www.thesmallbusinesscoach.com/blog/">Business Owner's Blog</a></li>
      <li>Jorn Lubkoll <em>(German)</em> - <a href="http://www.hv23.de/">Jorns Blog</a></li>
      <li>Juan Ignacio Acosta <em>(Spanish)</em> - <a href="http://www.juanignacioacosta.com/">Juan Ignacio Acosta</a></li>
      <li>Juan Luis Hortelano <em>(Spanish)</em> - <a href="http://www.tecnorantes.com/">Tecnorantes</a></li>
      <li>Karen Rands - <a href="http://myvirtualangelworld.com/">My Virtual Angel World</a></li>
      <li>Kelly Smith - <a href="http://www.kellysmith.com/">Made In Seattle</a></li>
      <li>Ken Hayes - <a href="http://kbhayes.com/">Ken Hayes</a></li>
      <li>Kevin Foong - <a href="http://www.generation247.net/">Generation 247</a></li>
      <li>Knox Massey - <a href="http://angelatlanta.wordpress.com/">Common Stock Not</a></li>
      <li>Kris Nair - <a href="http://krisnair.name/">Less Humans, More Robots</a></li>
      <li>Kurt Nybroe-Nielsen - <a href="http://knybroe.wordpress.com/">Knybroe's Blog</a></li>
      <li>Lance Wiggs - <a href="http://lancewiggs.com/">Lance Wiggs</a></li>
      <li>Larry Augustin - <a href="http://lmaugustin.typepad.com/">Larry Augustin's Weblog</a></li>
      <li>Lawrence Haddock - <a href="http://www.venturingcapital.com/">Venturing Capital</a></li>
      <li>Linda Ireland - <a href="http://customerexperienceforprofit.com/">The Customer Experience For Profit Blog</a></li>
      <li>Lluis Faus <em>(Spanish)</em> - <a href="http://lluisfaus.com/">El Blog De Lluis Faus</a></li>
      <li>Marc Hustvedt - <a href="http://seedwatcher.typepad.com/">seedWatcher</a></li>
      <li>Marc Nathan - <a href="http://bulldogfinancial.com/bullblog/">Bulldog Financial's Bullblog</a></li>
      <li>Marek Fodor <em>(Spanish)</em> - <a href="http://es.marekfodor.com/">Marek Fodor</a></li>
      <li>Mariano Ruani <em>(Spanish)</em> - <a href="http://www.inversorangel.com/">Inversor Angel</a></li>
      <li>Mark Adams - <a href="http://cluetrainee.com/">Cluetrainee's Blog...</a></li>
      <li>Mark Cuban - <a href="http://blogmaverick.com/">Blog Maverick</a></li>
      <li>Mark Fletcher - <a href="http://www.wingedpig.com/">Winged Pig</a></li>
      <li>Mark Pincus - <a href="http://markpincus.typepad.com/">Mark Pincus Blog</a></li>
      <li>Mark Sigal - <a href="http://www.thenetworkgarden.com/">The Network Garden</a></li>
      <li>Martin Tobias - <a href="http://www.deepgreencrystals.com/">Deep Green Crystals</a></li>
      <li>Martin Varsavsky - <a href="http://english.martinvarsavsky.net/">Blog Of An Entrepreneur</a></li>
      <li>Martin Zwilling - <a href="http://blog.startupprofessionals.com/">Startup Professionals Musings</a></li>
      <li>Michael Arrington - <a href="http://www.crunchnotes.com/">CrunchNotes</a></li>
      <li>Michael Jones - <a href="http://mjones.la/">Mike Jones Blog</a></li>
      <li>Michael Parekh - <a href="http://mp.blogs.com/">Michael Parekh On IT</a></li>
      <li>Miguel Valls - <a href="http://www.lateralthinking.biz/">Lateral Thinking</a></li>
      <li>Mitch Kapor - <a href="http://mkapor.posterous.com/">Mitch's Posterious</a></li>
      <li>Mitch Ratcliffe - <a href="http://ratcliffeblog.com/">RatcliffeBlog</a></li>
      <li>Morris Callaman - <a href="http://tumblr.callaman.us/">Morris Callaman</a></li>
      <li>Morten Wulff - <a href="http://drzelig.com/">Dr. Zelig aka Morten E. Wulff</a></li>
      <li>Nicola Gasperini <em>(Italian)</em> - <a href="http://nicolagasperini.com/">Digital Business Lab</a></li>
      <li>Nicolai Wadstrom - <a href="http://www.wadstrom.net/">Nicolai Wadstrom On Entrepreneurship</a></li>
      <li>Niel Robertson - <a href="http://parallax.blogs.com/">Parallax : Calculating Technology's Future</a></li>
      <li>Nikolaj Nyholm - <a href="http://radar.oreilly.com/nikolaj/">Nikolaj Nyholm | O'Reilly Radar</a></li>
      <li>Ouriel Ohayon - <a href="http://ouriel.typepad.com/">Ouriel Ohayon</a></li>
      <li>Paraic Hegarty - <a href="http://chaosmanagement.ie/blog/">The Business Of Technology</a></li>
      <li>Pascal Finette - <a href="http://blog.finette.co.uk/">Pascal Finette</a></li>
      <li>Pascal Mercier <em>(French)</em> - <a href="http://pascal.blogs.com/">Weblog De Pascal Mercier</a></li>
      <li>Patrick Lor - <a href="http://patricklor.typepad.com/">Patrick Lor</a></li>
      <li>Paul Buchheit - <a href="http://paulbuchheit.blogspot.com/">Paul Buchheit</a></li>
      <li>Paul Elosegui - <a href="http://blog.eucap.com/">EUCAP Capital Partners</a></li>
      <li>Paul Graham - <a href="http://www.paulgraham.com/articles.html">Essays</a></li>
      <li>Paula Bruno - <a href="http://www.chicksandbalances.com/index.php/blog">Chicks + Balances Blog</a></li>
      <li>Permjot Valia - <a href="http://www.businessangelblog.com/">Business Angel Blog</a></li>
      <li>Peter Schupbach <em>(German)</em> - <a href="http://peters.wordpress.com/">Peter Schupbach - NewBorn Blog</a></li>
      <li>Poh Kam Wong - <a href="http://connect-the-dots-singapore.blogspot.com/">Connect The Dots@Singapore</a></li>
      <li>Rajesh Jain - <a href="http://emergic.org/">Emergic: Rajesh Jain's Blog</a></li>
      <li>Rich Swier - <a href="http://swier.blogspot.com/">ZENtrepreneur</a></li>
      <li>Richard Wolpert - <a href="http://rwolpert.typepad.com/">Wolperts Blog</a></li>
      <li>Robert Ochtel - <a href="http://rochtel.wordpress.com/">Robert Ochtel's Blog</a></li>
      <li>Roberto Fernandez <em>(Spanish)</em> - <a href="http://www.roverto.net/">Roberto Fernandez</a></li>
      <li>Robin Klein - <a href="http://the-accelerator.blogspot.com/">The Accelerator Group (TAG)</a></li>
      <li>Rodolfo Carpintier <em>(Spanish)</em> - <a href="http://www.rodolfocarpintier.com/">Rodolfo Carpintier Santana</a></li>
      <li>Rodrigo Sepulveda - <a href="http://sepulveda.net/">Rodrigo Sepulveda</a></li>
      <li>Roger Ehrenberg - <a href="http://www.informationarbitrage.com/">Information Arbitrage</a></li>
      <li>Scott Kosch - <a href="http://www.scottkosch.blogspot.com/">Scott Kosch's Weblog</a></li>
      <li>Sean Ellis - <a href="http://startup-marketing.com/">Startup Marketing Blog</a></li>
      <li>Seth Goldstein - <a href="http://blog.sethgoldstein.com/">@seth</a></li>
      <li>Shantanu Bhagwat - <a href="http://global-themes.com/">Global Themes</a></li>
      <li>Sid Mohasseb - <a href="http://sidmohasseb.blogspot.com/">Sid Mohasseb</a></li>
      <li>Steve Levin - <a href="http://theswarm.wordpress.com/">The Swarm</a></li>
      <li>Thomas Madsen-Mygdal - <a href="http://bootstrapping.net/">Bootstrapping</a></li>
      <li>Thomas Rehder <em>(German)</em> - <a href="http://blog.sightseekermedien.de/">Videowerber's Weblog</a></li>
      <li>Tim Ferriss - <a href="http://www.fourhourworkweek.com/blog/">The Blog Of Author Tim Ferriss</a></li>
      <li>Tim Keane - <a href="http://www.timkeane.org/">Startups And Angels: Along The Way To Success</a></li>
      <li>Timothy Bernard Jones - <a href="http://tbjinvestments.typepad.com/">TBJ Investments, LLC</a></li>
      <li>Todd Dean - <a href="http://toddk4seattle.blogspot.com/">Keiretsu Forum Northwest</a></li>
      <li>Tom Higley - <a href="http://blog.tomhigley.com/">Back In The Saddle: Startup 5.0</a></li>
      <li>Vineet Buch - <a href="http://ventureexplorer.typepad.com/">Venture Explorer</a></li>
      <li>Vinit Nijhawan - <a href="http://entremeister.typepad.com/">Serial Entrepreneur, Venture Capitalist</a></li>
      <li>Wendy Lea - <a href="http://www.wendylea.com/blog/">Beyond The Obvious</a></li>
      <li>Yorihiko Katou <em>(Japanese)</em> - <a href="http://katou.jp/">Yorihiko Katou</a></li>
    </ul>
  </div>
</div>
